### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by xelanaiznac** [Mieze/IntelMausiEthernet#10]
hi. I'm a noob in compiling so forgive me if I'm wrong.
I'm trying to compile the 2.3 version but i found 2 errors:

could you help me please?
<img width="1130" alt="screen shot 2017-04-28 at 14 33 00" src="https://cloud.githubusercontent.com/assets/6823633/25528774/a05ec2dc-2c1f-11e7-9ac1-52e1df5a1428.png">
<img width="1135" alt="screen shot 2017-04-28 at 14 32 41" src="https://cloud.githubusercontent.com/assets/6823633/25528775/a0805fe6-2c1f-11e7-974f-2653134d5214.png">

**Comment by Mieze** [comment]
It's save to ignore these warnings.
