### ISSUE TITLE
reboot after attempt access smb share

### ISSUE THREAD

**Issue by clickerpw** [Mieze/IntelMausiEthernet#13]
reboot after attempt access smb share

**Comment by clickerpw** [comment]
mac os x 10.13
driver 2.3.0

**Comment by Mieze** [comment]
Fix your system because there is absolutely no indication for a driver problem in High Sierra (I've check the source code Apple published) and in case there was, I would have received hundreds of error reports. It's more likely that the system caches are messed up causing the crash.
