### ISSUE TITLE
Kernel panic 10.13.3

### ISSUE THREAD

**Issue by damuellen** [Mieze/IntelMausiEthernet#15]
My system crashes at boot time. Since the last Mac OS update.
The system boot again when I remove your kext, before the update, your driver has done me good services.

**Comment by Mieze** [comment]
That's a classic which usually gets reported after every major OS update and no, it's not a the driver, but a messed up system (most likely the system caches). Please fix your system and everything will be fine again!

**Comment by damuellen** [comment]
Ok thank you.
I have already delete the system caches and some preferences,
but I will investigated the problem further in the hope that you are right with your diagnosis.

**Comment by damuellen** [comment]
After I've deleted a few more files the machine is running again.
Thanks again for your great contribution to the hackintosh community. 😃

**Comment by cattyhouse** [comment]
> After I've deleted a few more files the machine is running again.
> Thanks again for your great contribution to the hackintosh community. 😃

Hi Can you tell what files did you delete? and how did you delete system caches? i'm having the same issues, thanks
