### ISSUE TITLE
I can't get WOL working

### ISSUE THREAD

**Issue by fttx** [Mieze/IntelMausiEthernet#17]
Hi mieze,

on Windows it is working properly, but when i shutdown the computer from macOS it turns back on right after the shutdown, or instead, sometimes it shuts down also the network interface (no led) and WOL doesn't work

Bios settings: 
Advanced/APM Configuration/ErP ready=disabled
Advanced/APM Configuration/Power On By PCI-E=enabled

Motherboard: ASUS z370-I
NIC: I219-V
Kext: IntelMausiEthernet v2.3.0

**Comment by Mieze** [comment]
That's not a bug, it's the specified behavior because macOS doesn't support WoL from S5.

**Comment by xenio** [comment]
After 1 week trying hundred of fix, patch etc, I just changed line 174 and 175 of IntelMausiEthernet.cpp to TRUE

wolCapable = true;
wolActive = true;

Recompiled the kext and WOL is now working as always was before I changed motherboard. Now I am on Asus Z370A Prime with Wake On Lan turned on in the Bios.

**Comment by fttx** [comment]
So it works even with S5 when you cut the power off completely

**Comment by xenio** [comment]
I am on Hackintosh and the pc is completly off (not sleep) only some motherboard leds are on.
You have to enable FixShutdown ACPI Patch in clover or the pc does not shutdown but always restart.
Se ti serve ti mando il kext compilato per provarlo.

**Comment by fttx** [comment]
Si, grazie filippo.tortomasi@gmail.com

**Comment by fttx** [comment]
I confirm that it works on hackintosh

**Comment by 2b** [comment]
Thanks a lot for the fix @xenio . Works great on the latest Mojave build.

@Mieze why don't you just turn on these parameters by default?
Thank you for your work btw.

**Comment by Mieze** [comment]
The driver works as designed because macOS doesn't support WoL from S5 so that there is no clean way to enable or disable it by the OS.

**Comment by fttx** [comment]
Maybe a solution could be to enable it through a clover boot flag?

**Comment by wmjlxl** [comment]
> I am on Hackintosh and the pc is completly off (not sleep) only some motherboard leds are on.
> You have to enable FixShutdown ACPI Patch in clover or the pc does not shutdown but always restart.
> Se ti serve ti mando il kext compilato per provarlo.

Hello xenio.

thanks so much, now my hackintosh can use WOL now.
but i find one issue. if i put my osx into sleep -> wake it up  and then power off it.

WOL will not work. 

any solution to fix it?

thanks

**Comment by xenio** [comment]
@wmjlxl I am sorry I have no idea, I am not a developer.

**Comment by hiradyazdan** [comment]
@Mieze I'm not sure if it's macOS directly and suspect it's more of the Clover DSDT/ACPI 
config issue. OS does not seem to be involved in this process.

**Comment by TokyoHam** [comment]
> After 1 week trying hundred of fix, patch etc, I just changed line 174 and 175 of IntelMausiEthernet.cpp to TRUE
> 
> wolCapable = true;
> wolActive = true;
> 
> Recompiled the kext and WOL is now working as always was before I changed motherboard. Now I am on Asus Z370A Prime with Wake On Lan turned on in the Bios.

Is there any chance you'd be able to share that kext with me? I have literally no idea how to compile a kext, but that fix of yours is literally the last thing I need to make my new rig PERFECT. lol ... If you could share it with me, it would be _greatly_ appreciated!

**Comment by maaeps** [comment]
@TokyoHam 
You can find such a kext [here](https://github.com/maaeps/IntelMausiEthernet-WOL/releases).

**Comment by TokyoHam** [comment]
> @TokyoHam
> You can find such a kext [here](https://github.com/maaeps/IntelMausiEthernet-WOL/releases).

Wow, that's amazing. Thank you so much!! Making a complete backup of my macOS drive right now, and then I'll give this a try. I can just remove the original IntelMausiEthernet.kext, and put this one in, instead? I don't need to clear NVRAM or rebuild kext cache (?) or anything like that?

**Comment by maaeps** [comment]
It seems like this does not work using OpenCore.
Has everyone managed to enable WOL using OpenCore?

**Comment by th0u** [comment]
@TokyoHam Thnx for the hint regarding WOL. 
After adjusting wolCapable = true; and wolActive = true and compiling, I was able to WOL my PC after it was shut down.
I use reFind + OpenCore 0.5.7/Catalina + Win10Pro (all on different disks)
Thnx.

**Comment by 1alessandro1** [comment]
> The driver works as designed because macOS doesn't support WoL from S5 so that there is no clean way to enable or disable it by the OS.

Is this still true?
Why is it working for @xenio ?

**Comment by Mieze** [comment]
Apple has never made any efforts to support WoL from S5 and will most likely never do. Therefore I have no plans to implement it as it might cause harm to those who don't need it.

On the other hand, IntelMausiEthernet is published under the GPL and everybody is free to customize it according to his or her needs. Technically it's not that hard to add this feature so that I think it's the best way to leave it to the users.

**Comment by 1alessandro1** [comment]
To enable WoL, is it enough to add the changes from this commit to IntelMausiEthernet.cpp?

https://github.com/acidanthera/IntelMausi/commit/46360d85bb201f9c828f88ee594b7e61c45d5a2d

and also, in the acidanthera repo, in the changelog they said they fixed I219 WoL functionality, so it's enabled by default? 
What do you think from these commits?

![image](https://user-images.githubusercontent.com/46293832/104793406-b355df80-57a2-11eb-8280-a00864e9bf66.png)

source: https://github.com/acidanthera/IntelMausi/commit/a2078d81a42f3bd8c2a291a0dfacb5f2ead09145
