### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by hrxind** [Mieze/IntelMausiEthernet#18]
IntelMausiEthernet.cpp 2066 line:
Taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value
IntelMausiEthernet.cpp 1973 line:
Unused variable 'index'

**Comment by Mieze** [comment]
1.) Unaligned pointers a no problem for x86 CPUs.
2.) Since I disabled TSO the corresponding function isn't used anymore.
3.) Unused variables are nothing to worry about.

**Comment by hrxind** [comment]
Ok.
So I use Xcode to open the IntelMausiEthernet project and Export it.
Thank you.
