### ISSUE TITLE
Kernel Panic after wake from sleep on 10.14.4

### ISSUE THREAD

**Issue by mrm4gic** [Mieze/IntelMausiEthernet#21]
The following happened twice after the machine was running stable with sleep&wake cycles over one to two days. The panic happens after the machine has been woken up.

System Info: i5-8400 on Gigabyte Z370n on 10.14.4

Anonymous UUID:       3D37AFB3-EABC-7148-634A-AF9D2B3A2167

Wed May  1 16:30:00 2019

*** Panic Report ***
panic(cpu 1 caller 0xffffff80138dd16d): Kernel trap at 0xffffff7f970097ad, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff8026838008, CR3: 0x000000001d4d5000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0xffffff80eb34c000, RCX: 0x0000000000000000, RDX: 0x0000000000000200
RSP: 0xffffff811e5a3e30, RBP: 0xffffff811e5a3eb0, RSI: 0xffffff802c9a0000, RDI: 0xffffff80eb34c000
R8:  0x0000000053af5700, R9:  0x0000000000989680, R10: 0x00000f5e6992e82d, R11: 0xffffff80141ecd00
R12: 0xffffff80eb34c000, R13: 0xfffffffbd0a4083b, R14: 0xffffff8026838000, R15: 0x0000000000000001
RFL: 0x0000000000010246, RIP: 0xffffff7f970097ad, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffff8026838008, Error code: 0x0000000000000000, Fault CPU: 0x1, PL: 0, VF: 1

Backtrace (CPU 1), Frame : Return Address
0xffffff811e5a3900 : 0xffffff80137af82d mach_kernel : _handle_debugger_trap + 0x47d
0xffffff811e5a3950 : 0xffffff80138eb795 mach_kernel : _kdp_i386_trap + 0x155
0xffffff811e5a3990 : 0xffffff80138dcf4a mach_kernel : _kernel_trap + 0x50a
0xffffff811e5a3a00 : 0xffffff801375cae0 mach_kernel : _return_from_trap + 0xe0
0xffffff811e5a3a20 : 0xffffff80137af247 mach_kernel : _panic_trap_to_debugger + 0x197
0xffffff811e5a3b40 : 0xffffff80137af093 mach_kernel : _panic + 0x63
0xffffff811e5a3bb0 : 0xffffff80138dd16d mach_kernel : _kernel_trap + 0x72d
0xffffff811e5a3d20 : 0xffffff801375cae0 mach_kernel : _return_from_trap + 0xe0
0xffffff811e5a3d40 : 0xffffff7f970097ad com.insanelymac.IntelMausiEthernet : __ZN10IntelMausi11rxInterruptEP18IONetworkInterfacejP11IOMbufQueuePv + 0x3b
0xffffff811e5a3eb0 : 0xffffff7f9700a084 com.insanelymac.IntelMausiEthernet : __ZN10IntelMausi17interruptOccurredEP8OSObjectP22IOInterruptEventSourcei + 0x5e
0xffffff811e5a3ed0 : 0xffffff8013e5947c mach_kernel : __ZN22IOInterruptEventSource12checkForWorkEv + 0x13c
0xffffff811e5a3f30 : 0xffffff8013e57562 mach_kernel : __ZN10IOWorkLoop15runEventSourcesEv + 0x1e2
0xffffff811e5a3f70 : 0xffffff8013e56abc mach_kernel : __ZN10IOWorkLoop10threadMainEv + 0x2c
0xffffff811e5a3fa0 : 0xffffff801375c0ce mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.insanelymac.IntelMausiEthernet(2.4.1d1)[88E228F4-3264-385C-84E9-3B7F99112336]@0xffffff7f97006000->0xffffff7f97026fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[C97E6457-FFDC-3B2D-B552-3AC7C6B76AA7]@0xffffff7f9445f000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[54C3F778-4B95-3093-A51D-D761607C96CB]@0xffffff7f94095000

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 keepsyms=1 debug=0x100 darkwake=0 

Mac OS version:
18E226

Kernel version:
Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64
Kernel UUID: 4170BF94-38B6-364F-A1B0-2F7C2C30F9A9
Kernel slide:     0x0000000013400000
Kernel text base: 0xffffff8013600000
__HIB  text base: 0xffffff8013500000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)

System uptime in nanoseconds: 16898172998005
last loaded kext at 16778541536064: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7f970a4000, size 32768)
last unloaded kext at 16738158074146: com.sicreative.VoltageShift	1.1 (addr 0xffffff7f970a4000, size 28672)
loaded kexts:
com.valvesoftware.SteamInput-DS4v1	4357.73.42
com.valvesoftware.SteamInput	4357.73.42
com.intel.driver.EnergyDriver	3.5.5
ru.joedm.SMCSuperIO	1.0.2
com.insanelymac.IntelMausiEthernet	2.4.1d1
as.vit9696.SMCProcessor	1.0.2
as.vit9696.VirtualSMC	1.0.2
as.vit9696.AppleALC	1.3.7
as.vit9696.WhateverGreen	1.2.8
as.vit9696.Lilu	1.3.5
com.apple.filesystems.afpfs	11.1
com.apple.nke.asp-tcp	8.0.2
com.apple.driver.AppleBluetoothMultitouch	96
com.apple.driver.AudioAUUC	1.70
com.apple.fileutil	20.036.15
com.apple.filesystems.autofs	3.0
com.apple.driver.AGPM	110.25.2
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.driver.AppleMCCSControl	1.5.6
com.apple.driver.AppleHDA	282.54
com.apple.driver.AppleGraphicsDevicePolicy	3.30.14
com.apple.AGDCPluginDisplayMetrics	3.30.14
com.apple.driver.AppleIntelKBLGraphics	12.0.8
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.11f4
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleIntelCFLGraphicsFramebuffer	12.0.8
com.apple.private.KextAudit	1.0
com.apple.filesystems.apfs	945.250.134
com.apple.driver.AppleVirtIO	2.1.3
com.apple.filesystems.hfs.kext	407.200.4
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.driver.AppleAHCIPort	329.200.2
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	190
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleXsanScheme	3
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.security.SecureRemotePassword	1.0
com.apple.driver.AppleBluetoothHIDKeyboard	208
com.apple.driver.AppleHIDKeyboard	208
com.apple.driver.IOBluetoothHIDDriver	6.0.11f4
com.apple.driver.AppleMultitouchDriver	2440.7
com.apple.driver.AppleInputDeviceSupport	2440.2
com.apple.kext.triggers	1.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.driver.DspFuncLib	282.54
com.apple.kext.OSvKernDSPLib	528
com.apple.driver.AppleGraphicsControl	3.30.14
com.apple.iokit.IOAVBFamily	740.1
com.apple.plugin.IOgPTPPlugin	740.2
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IONDRVSupport	530.51
com.apple.driver.AppleHDAController	282.54
com.apple.iokit.IOHDAFamily	282.54
com.apple.AppleGPUWrangler	3.30.14
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.AppleGraphicsDeviceControl	3.30.14
com.apple.iokit.IOAcceleratorFamily2	404.8
com.apple.iokit.IOGraphicsFamily	530.60
com.apple.iokit.IOSurface	255.4.2
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOAHCIBlockStorage	301.250.5
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.11f4
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.11f4
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.11f4
com.apple.iokit.IOBluetoothFamily	6.0.11f4
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.driver.AppleEFINVRAM	2.1
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.250.6
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	740.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF
Model: Macmini8,1, BootROM 220.207.27.0.0, 6 processors, Intel Core i5, 2,81 GHz, 8 GB, SMC 2.40f0
Graphics: UHD Graphics 630 (Desktop), UHD Graphics 630 (Desktop), spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR4, 2666 MHz, Micron Technology, 8ATF1G64AZ-2G6E1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
Bluetooth: Version 6.0.11f4, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: UHD Graphics 630 (Desktop), VGA compatible controller, Internal
PCI Card: 200 Series PCH HD Audio, Audio device, Internal
Serial ATA Device: ST2000LX001-1RG174, 2 TB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus:

**Comment by Mieze** [comment]
Please clean the system caches in order to resolve the issue! For instructions you might want to take a look at:

https://www.insanelymac.com/forum/topic/304235-intelmausiethernetkext-for-intel-onboard-lan/

**Comment by mrm4gic** [comment]
Clover Is being used to inject the kext but u cleaned it anyway using

sudo kextcache -I /

but the panic continues to happen after 1-2 days uptime.

**Comment by Mieze** [comment]
The system cache needs to be cleaned too: Please see:

[https://www.insanelymac.com/forum/topic/304235-intelmausiethernetkext-for-intel-onboard-lan/](url)

**Comment by mrm4gic** [comment]
forgot to mention before.

I followed the steps listed in that article

1) removed all files except directories and symlinks from /System/Library/Caches
2) rebooted
3) sudo kextcache -i /
4) rebooted

**Comment by DreamSeason** [comment]
Same here. It's stable as hell for 99.9999999% percent of the time. kernel panic rarely happened for my months usage. But it did happen recently after waking up. Before kernel panic, my hack has not been restarted for nearly half a month. Only sleep and wake cycles. 
`Anonymous UUID:       7AE3BE29-A073-5590-B817-8B8189395694

Thu Jul 25 20:30:51 2019

*** Panic Report ***
panic(cpu 0 caller 0xffffff80102db92d): Kernel trap at 0xffffff7f90d8f7f5, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff8045171008, CR3: 0x00000000256d5000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0xffffff83586d5000, RCX: 0xffffff83cff63e88, RDX: 0x0000000000000100
RSP: 0xffffff83cff63cd0, RBP: 0xffffff83cff63d50, RSI: 0xffffff805dae0000, RDI: 0xffffff83586d5000
R8:  0x0000000000000000, R9:  0x0000000000989680, R10: 0x0000000000000000, R11: 0xffffff8010bf2cc0
R12: 0xffffff83586d5000, R13: 0x0000000000000000, R14: 0xffffff8045171000, R15: 0x0000000000000000
RFL: 0x0000000000010246, RIP: 0xffffff7f90d8f7f5, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffff8045171008, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffff83cff637a0 : 0xffffff80101aea2d 
0xffffff83cff637f0 : 0xffffff80102e9e95 
0xffffff83cff63830 : 0xffffff80102db70a 
0xffffff83cff638a0 : 0xffffff801015bb40 
0xffffff83cff638c0 : 0xffffff80101ae447 
0xffffff83cff639e0 : 0xffffff80101ae293 
0xffffff83cff63a50 : 0xffffff80102db92d 
0xffffff83cff63bc0 : 0xffffff801015bb40 
0xffffff83cff63be0 : 0xffffff7f90d8f7f5 
0xffffff83cff63d50 : 0xffffff7f90d901ac 
0xffffff83cff63d70 : 0xffffff7f90d5f558 
0xffffff83cff63da0 : 0xffffff8010859df8 
0xffffff83cff63e10 : 0xffffff7f90d5f5c2 
0xffffff83cff63e60 : 0xffffff7f90d63837 
0xffffff83cff63ee0 : 0xffffff80104720d1 
0xffffff83cff63fa0 : 0xffffff801015b0ce 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONetworkingFamily(3.4)[633B919E-8F93-3ED4-9A29-894AB1E79D29]@0xffffff7f90d55000->0xffffff7f90d84fff
         com.insanelymac.IntelMausiEthernet(2.4)[245D729F-7D48-3FD1-8D74-7B5D06F7C06E]@0xffffff7f90d8c000->0xffffff7f90d9ffff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[633B919E-8F93-3ED4-9A29-894AB1E79D29]@0xffffff7f90d55000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[CC6A465F-5A24-304D-B9DF-8C27819CC214]@0xffffff7f90ab5000

BSD process name corresponding to current thread: kernel_task
Boot args: vm_compressor=2 

Mac OS version:
18F132

Kernel version:
Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Kernel UUID: 7C8BB636-E593-3CE4-8528-9BD24A688851
Kernel slide:     0x000000000fe00000
Kernel text base: 0xffffff8010000000
__HIB  text base: 0xffffff800ff00000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)

System uptime in nanoseconds: 190273371870184
last loaded kext at 153696265541968: com.apple.driver.AppleUSBAudio	315.6 (addr 0xffffff7f932d9000, size 413696)
last unloaded kext at 153898623245829: com.apple.driver.usb.cdc	5.0.0 (addr 0xffffff7f93219000, size 28672)
loaded kexts:
org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000	6.10.0
com.intel.driver.EnergyDriver	3.5.5
com.insanelymac.IntelMausiEthernet	2.4.0
as.vit9696.AppleALC	1.3.3
as.vit9696.WhateverGreen	1.2.8
as.vit9696.Lilu	1.3.5
com.rehabman.driver.USBInjectAll	0.7.1
org.mozodojo.W836x	1.3.1
org.netkas.FakeSMC	3.5.2
com.apple.filesystems.msdosfs	1.10
com.apple.driver.AppleBluetoothMultitouch	96
com.apple.filesystems.smbfs	3.3.2
com.apple.driver.AudioAUUC	1.70
com.apple.fileutil	20.036.15
com.apple.filesystems.autofs	3.0
com.apple.filesystems.ntfs	3.13
com.apple.driver.AppleGraphicsDevicePolicy	3.40.16
com.apple.AGDCPluginDisplayMetrics	3.40.16
com.apple.driver.AGPM	110.25.10
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.driver.AppleMCCSControl	1.5.9
com.apple.driver.AppleHDA	282.54
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.12f1
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleIntelKBLGraphics	12.0.9
com.apple.iokit.CSRBluetoothHostControllerUSBTransport	6.0.12f1
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.AppleIntelCFLGraphicsFramebuffer	12.0.9
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleVirtIO	2.1.3
com.apple.filesystems.hfs.kext	407.200.4
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.filesystems.apfs	945.260.7
com.apple.driver.AppleAHCIPort	329.260.5
com.apple.private.KextAudit	1.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	201
com.apple.security.TMSafetyNet	8
com.apple.driver.IOBluetoothHIDDriver	6.0.12f1
com.apple.driver.AppleMultitouchDriver	2450.1
com.apple.driver.AppleInputDeviceSupport	2440.2
com.apple.kext.triggers	1.0
com.apple.driver.AppleGraphicsControl	3.40.16
com.apple.driver.DspFuncLib	282.54
com.apple.kext.OSvKernDSPLib	528
com.apple.iokit.IOAVBFamily	740.1
com.apple.plugin.IOgPTPPlugin	740.2
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.driver.AppleSSE	1.0
com.apple.AppleGPUWrangler	3.40.16
com.apple.driver.AppleHDAController	282.54
com.apple.iokit.IOHDAFamily	282.54
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IONDRVSupport	530.51
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.12f1
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.12f1
com.apple.iokit.IOBluetoothFamily	6.0.12f1
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.AppleGraphicsDeviceControl	3.40.16
com.apple.iokit.IOAcceleratorFamily2	404.9
com.apple.iokit.IOGraphicsFamily	530.66
com.apple.iokit.IOSurface	255.5.4
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.iokit.IOSerialFamily	11
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.260.3
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	740.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1

EOF
Model: Macmini8,1, BootROM 220.260.170.0.0, 6 processors, Intel Core i7, 3.70 GHz, 32 GB, SMC 1.30f3
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 16 GB, DDR4, 2133 MHz, Team Group, TEAMGROUP-UD4-2133
Memory Module: BANK 1/DIMM0, 16 GB, DDR4, 2133 MHz, Team Group, TEAMGROUP-UD4-2133
Bluetooth: Version 6.0.12f1, 3 services, 26 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: Intel I219V2 PCI Express Gigabit Ethernet, Ethernet Controller, Ethernet
USB Device: USB 3.0 Bus
USB Device: Hub
USB Device: USB Optical Mouse
USB Device: Hub
USB Device: CSR8510 A10
USB Device: Composite Device
Thunderbolt Bus: 
`
