### ISSUE TITLE
2.5.0d and lag

### ISSUE THREAD

**Issue by linked67** [Mieze/IntelMausiEthernet#22]
Hi,

When i start Xcode, there is a sort of lag that cut somehow the network for some seconds. I can see video stream that stop or online game ping status going red and display lag of 20s.
Things go normal after this initial lag but only for some minutes, ater it's a sort of lag loop every maybe 5 minutes something like this.

Closing Xcode stop the lag.

Reverting to 2.4.0 fixed the issue. Only a minimal lag on xcode opening and everything fine after.

I use a Gigabyte z370 hd3p with latest mojave and clover.

Thanks

**Comment by Mieze** [comment]
This is definitely not a driver issue as the problem you described is far beyond the scope of an ethernet driver.

**Comment by leader86** [comment]
Me too, with v.2.5.0d  find some lag during last part of the boot and during shutdown.
Reverting to v.2.3.0 lag disappear.

I have Gigabyte Gigabyte GA-Z170X-Gaming 5, OSX Mojave 10.14.6

Regards.

**Comment by Mieze** [comment]
Fix your system because this is not a driver issue!

**Comment by leader86** [comment]
Could you be more specific, please?

**Comment by Mieze** [comment]
Honestly I have no idea where the cause of your problem lies but I know that these kind of things are far beyond the scope of a driver and that's why I'm telling you that you are on the wrong track. Maybe it's a linker error or something like that...

**Comment by linked67** [comment]
After a lot of testing and installed Mojave from scratch on a brand new SSD, i still see the issue.
Each time i open Xcode, even i don't open a project and just stay on the Xcode start screen, i can see this network lag.

When i have some steaming video on the screen or online video game with Xcode open too, apter some random minutes i see network lag. It's around 5 or 10s now every X minutes where there is no data. Video steam just stop and start 10s later, same for online video games.

All the network is like cut for some seconds and it can happen every 2 minutes, it's a real pain.

Reverting to v2.4 fixed the issue. I understand it's maybe not a driver issue but the v2.5 combined with Xcode clearly generate a problem that don't exist in v2.4 (and maybe earlier version too)
