### ISSUE TITLE
How to get the .kext file?

### ISSUE THREAD

**Issue by ibnYusrat** [Mieze/IntelMausiEthernet#23]
Hi..

I am complete hackintosh idiot. I was reading a hackintosh tutorial about getting gathering .kext files but I am not able to understand how do I get it from this repo.

Please help me understand. 

Thank you.

**Comment by j-autuick** [comment]
I am also curious about this.

**Comment by Mieze** [comment]
[Please see:]https://www.insanelymac.com/forum/topic/304235-intelmausiethernetkext-for-intel-onboard-lan/
