### ISSUE TITLE
The Network Kernel Extension API is now deprecated

### ISSUE THREAD

**Issue by athei** [Mieze/IntelMausiEthernet#24]
I just found this while glancing over the Catalina [changelog](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_beta_2_release_notes):

> The Network Kernel Extension API is now deprecated.

It seems that Apple wants us to port the network drivers to [DriverKit](https://developer.apple.com/documentation/driverkit) which is a userspace driver API. It might be several versions before the old interface gets removed. Just want to raise awareness.

**Comment by Mieze** [comment]
This driver doesn't use (and never did) the Network Kernel Extension API so that it won't be affected by the change at all.
