### ISSUE TITLE
How to compile project to kext file?

### ISSUE THREAD

**Issue by Drovosek01** [Mieze/IntelMausiEthernet#25]
Hello.
Rehabman in some of his projects and in the comments on the forum says to compile his project in .kext "file", you need to clone the git repository, then go to the terminal folder with the inclined repository and run the command "make".
I tried to do the same with your project, but, as you know, nothing came of it.
How can I compile your project?

Thank you for the kexts.

**Comment by arraystock** [comment]
This project does not use a Makefile, it uses Xcode's build system. Open the file `IntelMauseEthernet.xcodeproj` in Xcode, click the build button in the top left corner, then to open the folder containing the kext, expand the `Products` folder in the sidebar, right-click on the kext file and click `Show in Finder`.
