### ISSUE TITLE
2.5.0 not being injected into kernel by OpenCore 0.5.6

### ISSUE THREAD

**Issue by MacNB** [Mieze/IntelMausiEthernet#29]
OpenCore 0.5.6 boot log shows an error:
`11:014 05:628 OC: Prelink injection IntelMausiEthernet.kext (Intel Ethernet LAN) - Invalid Parameter`

...and the kext is not injected into the kernel.

Going back to version 2.4.1d1 works fine.

**Comment by gazzmanzx6** [comment]
I think these 2 are linked as it was with OpenCore 0.5.6 that I noticed the problem.
#28
