### ISSUE TITLE
Intel NUC 100baseTx

### ISSUE THREAD

**Issue by digitalroadies** [Mieze/IntelMausiEthernet#3]
I have an Intel NUC [5i7RYH](http://www.intel.com/content/www/us/en/nuc/nuc-kit-nuc5i7ryh.html) with your driver the interfaces only works at 100baseTX.  If I manually set it to Gig I get "Not Connected".  I can provide you with any logs / trobuleshooting.

**Comment by Mieze** [comment]
Please send me your kernel logs including at least one complete boot sequence.
