### ISSUE TITLE
IntelMausiEthernet breaks wake on network

### ISSUE THREAD

**Issue by cattyhouse** [Mieze/IntelMausiEthernet#31]
- issue
    - Both Acidanthera/IntelMausi 1.03 and Mieze/IntelMausiEthernet(96a7dc2ef28520d521d3db82701ba06230999517) latest commit breaks wake on network on my hackintosh
    - while Acidanthera/IntelMausi 1.02 works perfectly fine. 

- hardware:
Device ID: 15BC
Vendor 8086
SubVendor 1849
Name: Intel I219-V
Path: IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/GLAN@1F,6
- macOS 10.15.5
- tools i used to wake mac: 
http://ahh.sourceforge.net/wol/

- command i used to wake mac: 
`wol 'hackintosh's MAC address'`
and then try pinging the mac's ip address (which is a manual address )

you may want to test to verify. thanks

**Comment by nyhtml** [comment]
As a curious Hackintosh user, was this with OpenCore or Clover? And by the way, your issue may be related to Issue #17.

https://github.com/Mieze/IntelMausiEthernet/issues/17

**Comment by cattyhouse** [comment]
I use OpenCore 0.5.9

**Comment by cattyhouse** [comment]
In acidanthera’s version 1.0.2 , the wolCapable was also set to false in the code, but wol works when mac is sleeping. I don’t think turning this on will help.

**Comment by cattyhouse** [comment]
Because of these codes: 


```cpp


    /* Setup power management. */
    if (provider->findPCICapability(kIOPCIPowerManagementCapability, &pmCapOffset)) {
        pmCap = provider->extendedConfigRead16(pmCapOffset + kIOPCIPMCapability);
        DebugLog("Ethernet [IntelMausi]: PCI power management capabilities: 0x%x.\n", pmCap);
        
        if (pmCap & (kPCIPMCPMESupportFromD3Cold | kPCIPMCPMESupportFromD3Hot)) {
            wolCapable = true;
            DebugLog("Ethernet [IntelMausi]: PME# from D3 (cold/hot) supported.\n");
        }
        pciPMCtrlOffset = pmCapOffset + kIOPCIPMControl;
    } else {
        IOLog("Ethernet [IntelMausi]: PCI power management unsupported.\n");
    }
    provider->enablePCIPowerManagement();

```

**Comment by cattyhouse** [comment]
just tried to set these 2 options to true, and wol works now, thanks for your information.
 
https://github.com/Mieze/IntelMausiEthernet/blob/b1cafc7e07eeec32ee65eac0c8a01d6c4653cb59/IntelMausiEthernet/IntelMausiEthernet.cpp#L180-L181 

then i think in latest commit, something is wrong here : 

https://github.com/Mieze/IntelMausiEthernet/blob/b725a08ebc149ae2b4367c3fc700904736368514/IntelMausiEthernet/IntelMausiHardware.cpp#L107-L110

**Comment by nyhtml** [comment]
@cattyhouse 

Cool. 😀 And with OpenCore 0.5.9. 👍

I'm still waiting the rest of my parts to finish my second build to make the switch. Shipping is slower now due to the pandemic so I'm stuck waiting for parts from overseas and glad I didn't pull apart my current Clover system (yet) to upgrade.

**Comment by Mieze** [comment]
No, there is nothing wrong with the driver and your issue also has nothing to do with the latest commit. WoL support works as specified because it is only enabled when the hardware reports that it supports WoL. Otherwise it will be disabled. In case you've got trouble getting WoL to work, please fix your system to report WoL support properly.

**Comment by cattyhouse** [comment]
@Mieze Hi, Mieze thanks for your reply, can you take a look at the debug log of version 1.0.3 (wol does not work during sleep) and 1.0.2 (wol works during sleep) ? 

[102.debug-new.log](https://github.com/Mieze/IntelMausiEthernet/files/4797225/102.debug-new.log)
[103.debug-new.log](https://github.com/Mieze/IntelMausiEthernet/files/4797226/103.debug-new.log)
