### ISSUE TITLE
Intel I225-V

### ISSUE THREAD

**Issue by mbarbierato** [Mieze/IntelMausiEthernet#34]
Hello,
have you plan to integrate the 400 series, i have gigabyte z490 with intel I225-V 

Thank you
Massimiliano

**Comment by Mieze** [comment]
No, because I225LM is natively supported by AppleIntelI210Ethernet.kext. In order to make I225V work too, all you have to do is faking the dev id of I225LM.

**Comment by mbarbierato** [comment]
Ok, Thank you
