### ISSUE TITLE
Kernel panic on boot

### ISSUE THREAD

**Issue by phreakymonkey** [Mieze/IntelMausiEthernet#35]
As detailed [here](https://www.reddit.com/r/hackintosh/comments/j3c651/apple_intel_ethernet_driver_causing_kernel_panic/), I can't boot due to a problem with the AppleIntelI210Ethernet driver.
![IC2T0He](https://user-images.githubusercontent.com/2574410/94853712-c1d3f180-0466-11eb-9a8a-f27753ec7c34.jpg)

I've tried both the acidanthera version as well as this one. Someone on reddit suggested it was something to do with [this line of code](https://github.com/Mieze/IntelMausiEthernet/blob/b1cafc7e07eeec32ee65eac0c8a01d6c4653cb59/IntelMausiEthernet/IntelMausiEthernet.cpp#L1774), as it seems to fail when trying to validate the NVM checksum. Would increasing the number of attempts help, I wonder?

**Comment by Mieze** [comment]
Two rhetorical questions:

First, have you ever looked at the picture of the kernel panic above?

Second, what does this kernel panic have to do with IntelMausiEthernet?

I'll give you the answer: nothing! Please fix your system!!!
