### ISSUE TITLE
IntelMausi Internet does not work on Asus Q170S1

### ISSUE THREAD

**Issue by b33b** [Mieze/IntelMausiEthernet#40]
I would like to inform you about a problem with the Internet plant on the ASUS Q170S1 motherboard
I would like to inform you that the Intel I219LM chip

The problem is as follows.
The system does not see Etnernet. There is a constant status in the settings: the cable is disconnected

The system does not see that the cable is connected.

This problem also occurred with other users, on Mojave, Catalina and the latest version.

Used version 1.0.5 of Realsese on 11.2.3, 10.15.7 but no luck.
Also tried the DEBUG version of that logs, but I could not hook them

Please understand this situation
[asus q170s1.ioreg.zip](https://github.com/Mieze/IntelMausiEthernet/files/6292773/asus.q170s1.ioreg.zip)

**Comment by nyhtml** [comment]
1.0.5 is is a fork under Acidanthera so you're in the wrong place. 😂

I think that their fork works better with VirtualSMC so if you're using Clover with FakeSMC, try VirtualSMC on USB (not your boot drive) and then if boots successfully, copy to the boot drive.

My system used FakeSMC, VooDooHDA and IME for a good while but as I need to run newrr macOS version, I later switched to VirtualSMC, AppleALC and stopped  IME at 2.4 as it works beautifully.

**Comment by vannadium1788** [comment]
> 1.0.5 is is a fork under Acidanthera so you're in the wrong place. 😂
> 
> I think that their fork works better with VirtualSMC so if you're using Clover with FakeSMC, try VirtualSMC on USB (not your boot drive) and then if boots successfully, copy to the boot drive.
> 
> My system used FakeSMC, VooDooHDA and IME for a good while but as I need to run newrr macOS version, I later switched to VirtualSMC, AppleALC and stopped IME at 2.4 as it works beautifully.

I also tested this author's version, but the internet doesn't work either.
Does the author have any support at all?
Where to write to him so that he can fix his problem

**Comment by nyhtml** [comment]
In the README.md it says "Support requests here on Github will be ignored!" So you may want to go to the link provided in the page. I would also try find v2.4 or lower (very easy using Bing Search) as that often fixes the issue and don't update it accidentally with app like Clover Configurator after it works.
