### ISSUE TITLE
Link goes down during file copy

### ISSUE THREAD

**Issue by tebruno99** [Mieze/IntelMausiEthernet#5]
Hello,
When I copy about 2,000 files (10gb) with Finder to a Linux SMB share after a few minutes the Mausi driver reports that the link has gone down.

```
Link down on en0
Link up on en0, 1-Gigabit, Full-duplex, No flow-control
Tx stalled? Resetting chipset. txDirtyDescIndex=0, STATUS=0x40080083, TCTL=0x3103f0fa.
```

The link continues to reset, go down and come back up until reboot.

This ONLY happens with finder. I was able to rsync my entire disk 400+ GB via rsync+ssh and rsync+smb the issue never happens, but with Finder+smb it is fairly reproducible.  Is there anything I can give to you from my system that will help debug?

Intel i7-6700K
Asus Pro Gaming
Ethernet i219
OSX 10.11.5

**Comment by tebruno99** [comment]
[IntelMausi-Log.txt](https://github.com/Mieze/IntelMausiEthernet/files/367836/IntelMausi-Log.txt)

**Comment by skitchin** [comment]
I have the same problem when copying thousand of files and sometimes links goes down when I reboot the router.

Intel i7-6700K
Asus Maximus Gene VIII
Ethernet i219v
OSX 10.11.5

**Comment by Mieze** [comment]
This is a power management issue. I already explained it in depth. You'll have to patch your SSDT in order to resolve it. Please see: http://www.insanelymac.com/forum/topic/304235-intelmausiethernetkext-for-intel-onboard-lan/

**Comment by tebruno99** [comment]
Thank you Mieze, I tried to google around and didn't find anything. Great work!  Sorry for the noise

**Comment by tebruno99** [comment]
Mieze,
  I attempted the SSDT patch that you posted. I have an i7-6700K and the problem continued to exist.  I switched to an Apple branded 82574L PCI-Express caed that uses Intel82574L.kext and the issue hasn't happened again.  If it was a Skylade power management issue wouldn't that be reflected in all cards?

I have to reply here because InsanelyMac forums says I'm not allowed to comment/reply on your original thread :(

**Comment by Sander37** [comment]
Hi Mieze,
I've the same problem as tebruno99 discribes, when copying large files (10G) in most cases the en0 link goes down at some point. I have the (Piker Alpha)CPUPM SSDT patch installed for my i7-6700K. (Asus Z170 ProGaming.bios1904 with OSX10.11.6, 10.11.5 had the same problem)

sometimes the link is restored, sometimes i get a "cable disconnected" and have to reboot to get a connection again.

ps. are there any non Asus users also experiencing this problem?

**Comment by tomhumphrey** [comment]
I've got the same issue as well on a GA-Z170N-Wifi with an Intel i7-6700k

**Comment by tomhumphrey** [comment]
I'm getting similar on Gigabyte GA-Z170N-WIFI with an i7-6700k. I've also noticed if I hammer the PC (doing something like 3 video conversions at once) the ethernet drops and says the cable has been unplugged. I used Piker-Alpha's ssdtPRGen script to generate my SSDT. I've also tried your suggestions in the thread but have seen my P states disappear after doing so.

**Comment by Sander37** [comment]
2.2.0d4 fixed this issue.

**Comment by thinkwing** [comment]
I've the same problem as tebruno99 discribes on Gigabyte B150M with i3-6100, using 2.2.0 version.
