### ISSUE TITLE
Intel I219V2 reconnect issue

### ISSUE THREAD

**Issue by clickerpw** [Mieze/IntelMausiEthernet#6]
after start hackintosh lan card works perfect but if ethernet cable disconnect first and connect after
 in system preferences  lan card status  info  is lan cable connected and  has not IP address.
Used v2.2.0
VID   0x8086
PID   0x15b8
Motherboard ASRock B150M Pro4

**Comment by Mieze** [comment]
I don't know what you are doing wrong but I can rule out a driver issue. At first glance looks more like a DHCP related problem. For further instructions please see http://www.insanelymac.com/forum/topic/304235-intelmausiethernetkext-for-intel-onboard-lan/?p=2107186
or post in this thread.
